import { Dna, Sparkles, Layers, Clapperboard } from 'lucide-react'

const features = [
  {
    icon: Dna,
    title: 'Brand DNA Extraction',
    desc: 'We analyze your website and logo with GPT-4o to extract color palette, tone, taglines, and products into a living brandbook.',
  },
  {
    icon: Sparkles,
    title: 'AI Mascot Generation',
    desc: '4 unique mascot variations generated by PixVerse, tailored to your brand personality, gender preference, and character style.',
  },
  {
    icon: Layers,
    title: 'Character Sheet',
    desc: 'Full front, side, and back views of your chosen mascot — ready for video generation and use across all your brand assets.',
  },
  {
    icon: Clapperboard,
    title: '30-Second Brand Video',
    desc: '5 cinematic clips featuring your mascot, auto-generated from your brandbook and stitched into a shareable MP4 video.',
  },
]

export default function Features() {
  return (
    <section id="features" className="mx-auto max-w-6xl px-12 pb-28">
      <p className="mb-4 text-xs font-semibold uppercase tracking-[3px] text-accent">
        What You Get
      </p>
      <h2
        className="mb-16 font-display uppercase leading-none tracking-wide"
        style={{ fontSize: 'clamp(40px, 5vw, 72px)' }}
      >
        Everything your
        <br />
        <span className="text-accent">brand needs.</span>
      </h2>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {features.map((f) => {
          const Icon = f.icon
          return (
            <div
              key={f.title}
              className="group rounded-xl border border-border bg-surface p-9 transition-all duration-300 hover:-translate-y-0.5 hover:border-accent/20 hover:bg-surface2"
            >
              <div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl border border-accent/20 bg-accent/10">
                <Icon className="h-5 w-5 text-accent" />
              </div>
              <h3 className="mb-2.5 text-base font-semibold text-text">{f.title}</h3>
              <p className="text-sm leading-relaxed text-muted">{f.desc}</p>
            </div>
          )
        })}
      </div>
    </section>
  )
}
