import { Dna, Sparkles, Layers, Clapperboard } from 'lucide-react'

const features = [
  {
    icon: Dna,
    title: 'Brand DNA Extraction',
    desc: 'We analyze your website and logo with GPT-4o to extract color palette, tone, taglines, and products into a living brandbook.',
  },
  {
    icon: Sparkles,
    title: 'AI Mascot Generation',
    desc: '4 unique mascot variations generated by PixVerse, tailored to your brand personality, gender preference, and character style.',
  },
  {
    icon: Layers,
    title: 'Character Sheet',
    desc: 'Full front, side, and back views of your chosen mascot — ready for video generation and use across all your brand assets.',
  },
  {
    icon: Clapperboard,
    title: '30-Second Brand Video',
    desc: '5 cinematic clips featuring your mascot, auto-generated from your brandbook and stitched into a shareable MP4 video.',
  },
]

export default function Features() {
  return (
    <section id="features" className="max-w-6xl mx-auto px-12 pb-28">
      <p className="text-accent text-xs font-semibold tracking-[3px] uppercase mb-4">What You Get</p>
      <h2
        className="font-display uppercase leading-none tracking-wide mb-16"
        style={{ fontSize: 'clamp(40px, 5vw, 72px)' }}
      >
        Everything your<br />
        <span className="text-accent">brand needs.</span>
      </h2>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {features.map((f) => {
          const Icon = f.icon
          return (
            <div
              key={f.title}
              className="group bg-surface border border-border rounded-xl p-9 hover:bg-surface2 hover:-translate-y-0.5 hover:border-accent/20 transition-all duration-300"
            >
              <div className="w-11 h-11 bg-accent/10 border border-accent/20 rounded-xl flex items-center justify-center mb-5">
                <Icon className="w-5 h-5 text-accent" />
              </div>
              <h3 className="text-base font-semibold text-text mb-2.5">{f.title}</h3>
              <p className="text-sm text-muted leading-relaxed">{f.desc}</p>
            </div>
          )
        })}
      </div>
    </section>
  )
}
